language: ruby
rvm:
- 2.6.3
 
script: ./bin/cibuild
 
before_script:
 - chmod +x ./bin/cibuild
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: awesome-doge/awesome-doge.github.io
  local_dir: _site
  target_branch: master
  on:
    branch: master
